import Head from "next/head";
import { useEffect } from "react";
import { Col, Row, Spin, Typography } from "antd";
import { MainLayout } from "../layouts/mainLayout";
import { SideMenu, Carousel, BusinessPartners, ProductCollection } from "../components";
import { useSelector, useDispatch } from "react-redux";
import { getRecommendProductList } from "../redux/reducer/recommendProduct/slice";
import { useTranslation } from "react-i18next";

const sideImage = "/assets/images/sider_2019_12-09.png";
const sideImage2 = "/assets/images/sider_2019_02-04.png";
const sideImage3 = "/assets/images/sider_2019_02-04-2.png";

export default function Home() {
  const { t } = useTranslation();
  const dispatch = useDispatch();
  const loading = useSelector((state) => state.recommendProduct.loading);
  const error = useSelector((state) => state.recommendProduct.error);
  const recommendProductList = useSelector(
    (state) => state.recommendProduct.recommendProductList
  );

  useEffect(() => {
    dispatch(getRecommendProductList());
  }, []);

  if (loading) {
    return (
      <Spin
        size={"large"}
        style={{
          marginTop: 200,
          marginBottom: 200,
          marginLeft: "auto",
          marginRight: "auto",
          width: "100%",
        }}
      />
    );
  }
  if (error) {
    return <div>网站出错：{error}</div>;
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Row style={{ marginTop: 20 }}>
          <Col span={6}>
            <SideMenu />
          </Col>
          <Col span={18}>
            <Carousel />
          </Col>
        </Row>
        <ProductCollection
          title={
            <Typography.Title level={3} type="warning">
              {t("home_page.hot_recommended")}
            </Typography.Title>
          }
          sideImage={sideImage}
          products={recommendProductList[0].touristRoutes}
        />
        <ProductCollection
          title={
            <Typography.Title level={3} type="danger">
              {t("home_page.new_arrival")}
            </Typography.Title>
          }
          sideImage={sideImage2}
          products={recommendProductList[1].touristRoutes}
        />
        <ProductCollection
          title={
            <Typography.Title level={3} type="success">
              {t("home_page.domestic_travel")}
            </Typography.Title>
          }
          sideImage={sideImage3}
          products={recommendProductList[2].touristRoutes}
        />
        <BusinessPartners />
      </MainLayout>
    </>
  );
}
